---
kind: pipeline
type: docker
name: Java Maven Test

trigger:
  branch:
    - master

steps:
  - name: settings
    image: md5lukas/drone-mvn-settings
    settings:
      servers:
        - id: woolgens-network
          username: woolgens-default
      serverSecrets:
        from_secret: MAVEN_SERVER_SECRETS
  - name: buildtools
    image: alpine/git
    commands:
      - mkdir buildtools
      - cd buildtools
      - apk update
      - apk upgrade
      - apk add maven
      - apk add openjdk16-jre
      - apk add wget
      - wget https://hub.spigotmc.org/jenkins/job/BuildTools/132/artifact/target/BuildTools.jar
      - java -jar BuildTools.jar --rev 1.17.1
      - java -jar BuildTools.jar --rev 1.17.1 --compile craftbukkit
  - name: testing
    image: maven
    depends_on: [settings, buildtools]
    commands:
      - mvn -U test -s settings.xml